### ISSUE TITLE
Slicer GUI

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [openvpi/audio-slicer#13]
Nothing happen when click `slicer-gui.exe`.

Version: `v1.2.0`

### Video

https://github.com/openvpi/audio-slicer/assets/73665622/da9df255-3f79-4227-8fb5-b3e9b834bbab

**Comment by flutydeer** [comment]
Hi, I'm the developer of audio slicer gui. Please check if there is a "log" folder.

**Comment by GreatestOfAllTimee** [comment]
there is no "log" folder in version `v1.2.0`.

**Comment by flutydeer** [comment]
I tried to fix this issue in [v1.2.1](https://github.com/flutydeer/audio-slicer/releases/tag/v1.2.1), please try it and give me a feedback.

**Comment by GreatestOfAllTimee** [comment]
thank you so much, it fixed in `v1.2.1 `
