### ISSUE TITLE
在导入方法时出现了问题

### ISSUE THREAD

**Issue by tori-hotaru** [openvpi/audio-slicer#2]
在按照提出的代码尝试切片时，发现程序无法调用Slicer中的slice方法，问题如图，不知道是哪里的问题，麻烦大佬解答
<img width="1010" alt="截屏2022-10-13 18 25 45" src="https://user-images.githubusercontent.com/58972377/195573343-15b17a1f-13a3-4ca1-94cd-cb20ee2e7c66.png">

**Comment by yqzhishen** [comment]
你好，很抱歉我没有遇到过这种问题。请问你是将 `slicer` 作为一个模块安装了吗？能否尝试一下在一个干净的 Python 环境中是否可以运行成功呢？

**Comment by yqzhishen** [comment]
看起来原因是你 `pip install` 了一个名为 `slicer` 的同名模块，该模块并非由我编写，而程序执行 `import` 时优先匹配了该模块。本仓库并未上架 PyPI，要使用此仓库的脚本，你无需手动安装，只需将 `slicer.py` 复制到自己的目录后 `import` 即可，程序会通过文件名进行匹配。
要解决你上面的问题，请卸载那个无关的模块：
```shell
pip uninstall slicer
```
