### ISSUE TITLE
有没有办法能限制切出来音频的最大长度呢

### ISSUE THREAD

**Issue by 3yude** [openvpi/audio-slicer#8]

**Comment by yqzhishen** [comment]
不能，因为你永远想象不到一个人能有多大的肺活量

**Comment by kslz** [comment]
你可以尝试将切好的音频按长度降序排列，选出过长的那些然后以更小的粒度来进行二次切割

**Comment by kslz** [comment]
话说我有一个曲线救国的方式，你可以用一个叫videosrt pro 的软件，是用来生成字幕的，它用了阿里云的录音转文字接口，而那个接口会返回每个字符的起止时间，基本相当于mfa了，这个软件靠这个支持最大字幕长度，你也可以通过自己请求这个接口，通过时间戳进行截取。如果你想找不要钱的，可以用标贝的语音评测，也有类似的功能，暂时免费。不过这摊子就大了...
